extends: default

ignore: |
  test-charts/*/templates/

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
  comments:
    min-spaces-from-content: 1
  document-start: disable
  braces: disable
  truthy: disable
