name: "git-diff"
version: "0.1.0"
usage: "helm git-diff [flags] [CHART...]"
description: |
  Compare rendered Kubernetes manifests between git commits.

  Automatically detects changed charts or compare specific charts.
  Shows unified diff of rendered manifests including uncommitted changes.
ignoreFlags: false
platformCommand:
  - command: ${HELM_PLUGIN_DIR}/bin/helm-git-diff
  - os: windows
    command: ${HELM_PLUGIN_DIR}\bin\helm-git-diff.exe
platformHooks:
  install:
    - command: ${HELM_PLUGIN_DIR}/install-plugin.sh
    - os: windows
      command: pwsh
      args:
        - -c
        - ${HELM_PLUGIN_DIR}/install-plugin.sh
  update:
    - command: ${HELM_PLUGIN_DIR}/install-plugin.sh
    - os: windows
      command: pwsh
      args:
        - -c
        - ${HELM_PLUGIN_DIR}/install-plugin.sh
